import * as Knex from 'knex';
import { TABLE, CREATED_BY } from '@common/constants';
import { uuidV4 } from '@common/utilities';

const templates: any[] = [
  {
    id: uuidV4(),
    name: 'Banking Transactions',
    name_ar: 'Banking Transactions',
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    name: 'FATCA',
    name_ar: 'FATCA',
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    name: 'CRS',
    name_ar: 'CRS',
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    name: 'KYC (Know Your Customer)',
    name_ar: 'KYC (Know Your Customer)',
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
];

const sections: any[] = [
  {
    id: uuidV4(),
    name: 'What are the anticipated cash transactions on your account',
    name_ar: 'What are the anticipated cash transactions on your account',
    level: 'level 1',
    template_id: templates[0].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    name: 'Retrieving data. Wait a few seconds and try to cut or copy again.',
    name_ar:
      'Retrieving data. Wait a few seconds and try to cut or copy again.',
    level: 'level 1',
    template_id: templates[0].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    name: 'Individual Certification',
    name_ar: 'Individual Certification',
    level: 'level 1',
    template_id: templates[1].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    name: 'Personal Details',
    name_ar: 'Personal Details',
    level: 'level 1',
    template_id: templates[3].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    name: 'Professional Details',
    name_ar: 'Professional Details',
    level: 'level 1',
    template_id: templates[3].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    name: 'Residential Details',
    name_ar: 'Residential Details',
    level: 'level 1',
    template_id: templates[3].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    name: 'Additional Documents',
    name_ar: 'Additional Documents',
    level: 'level 1',
    template_id: templates[3].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    name: 'Country / Jurisdiction of tax residence',
    name_ar: 'Country / Jurisdiction of tax residence',
    level: 'level 1',
    template_id: templates[2].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    name: 'TIN',
    name_ar: 'TIN',
    level: 'level 1',
    template_id: templates[2].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    name: 'If TIN not available tick the reasons',
    name_ar: 'If TIN not available tick the reasons',
    level: 'level 1',
    template_id: templates[2].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    name:
      'Please explain in the following boxes why you are unable to obtain a TIN if you selected reason Babove.',
    name_ar:
      'Please explain in the following boxes why you are unable to obtain a TIN if you selected reason Babove.',
    level: 'level 1',
    template_id: templates[2].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
];

const questions: any[] = [
  {
    id: uuidV4(),
    title: 'Purpose of Account',
    title_ar: 'Purpose of Account',
    type: 'dropdown',
    rules: '{required: true}',
    section_id: sections[0].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    title: 'Cash Deposit',
    title_ar: 'Cash Deposit',
    type: 'checkbox',
    rules: '{required: true}',
    section_id: sections[0].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    title: 'Cash Withdrawal',
    title_ar: 'Cash Withdrawal',
    type: 'checkbox',
    rules: '{required: true}',
    section_id: sections[0].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    title: 'Cheque Deposit',
    title_ar: 'Cheque Deposit',
    type: 'checkbox',
    rules: '{required: true}',
    section_id: sections[0].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    title: 'Internal Transfers to KFHB Accounts',
    title_ar: 'Internal Transfers to KFHB Accounts',
    type: 'checkbox',
    rules: '{required: true}',
    section_id: sections[1].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    title: 'Outgoing International Transfers',
    title_ar: 'Outgoing International Transfers',
    type: 'checkbox',
    rules: '{required: true}',
    section_id: sections[1].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    title: 'Transfers to other banks in Bahrain',
    title_ar: 'Transfers to other banks in Bahrain',
    type: 'checkbox',
    rules: '{required: true}',
    section_id: sections[1].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    title: 'Incoming International Transfers',
    title_ar: 'Incoming International Transfers',
    type: 'checkbox',
    rules: '{required: true}',
    section_id: sections[1].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    title: 'Are you a US Citizen?',
    title_ar: 'Are you a US Citizen?',
    type: 'checkbox',
    rules: '{required: true}',
    section_id: sections[2].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    title: 'Are you a US Tax Resident?',
    title_ar: 'Are you a US Tax Resident?',
    type: 'checkbox',
    rules: '{required: true}',
    section_id: sections[2].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    title: 'Were you born in the US?',
    title_ar: 'Were you born in the US?',
    type: 'checkbox',
    rules: '{required: true}',
    section_id: sections[2].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    title:
      'Are you a tax resident in any other country other than the Kingdom of Bahrain or US?',
    title_ar:
      'Are you a tax resident in any other country other than the Kingdom of Bahrain or US?',
    type: 'checkbox',
    rules: '{required: true}',
    section_id: sections[2].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    title: 'Highest Education Degree',
    title_ar: 'Highest Education Degree',
    type: 'dropdown',
    rules: '{required: true}',
    section_id: sections[3].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    title: 'Source of Funds',
    title_ar: 'Source of Funds',
    type: 'dropdown',
    rules: '{required: true}',
    section_id: sections[3].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    title: 'Are you Politically Exposed?',
    title_ar: 'Are you Politically Exposed?',
    type: 'checkbox',
    rules: '{required: true}',
    section_id: sections[3].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    title: 'Country of Birth',
    title_ar: 'Country of Birth',
    type: 'dropdown',
    rules: '{required: true}',
    section_id: sections[3].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    title: 'Type of Employment',
    title_ar: 'Type of Employment',
    type: 'dropdown',
    rules: '{required: true}',
    section_id: sections[4].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    title: 'Company Name',
    title_ar: 'Company Name',
    type: 'text',
    rules: '{required: true}',
    section_id: sections[4].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    title: 'Monthly Income',
    title_ar: 'Monthly Income',
    type: 'dropdown',
    rules: '{required: true}',
    section_id: sections[4].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    title: 'Job Title',
    title_ar: 'Job Title',
    type: 'text',
    rules: '{required: true}',
    section_id: sections[4].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    title: 'Flat Number',
    title_ar: 'Flat Number',
    type: 'text',
    rules: '{required: true}',
    section_id: sections[5].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    title: 'Building Number',
    title_ar: 'Building Number',
    type: 'text',
    rules: '{required: true}',
    section_id: sections[5].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    title: 'Road',
    title_ar: 'Road',
    type: 'text',
    rules: '{required: true}',
    section_id: sections[5].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    title: 'Block Number',
    title_ar: 'Block Number',
    type: 'text',
    rules: '{required: true}',
    section_id: sections[5].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    title: 'Area',
    title_ar: 'Area',
    type: 'dropdown',
    rules: '{required: true}',
    section_id: sections[5].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    title: 'Other Contach Number',
    title_ar: 'Other Contach Number',
    type: 'text',
    rules: '{required: true}',
    section_id: sections[5].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    title: 'Select Proof of Address',
    title_ar: 'Select Proof of Address',
    type: 'dropdown',
    rules: '{required: true}',
    section_id: sections[6].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    title: 'Upload Proof of Address',
    title_ar: 'Upload Proof of Address',
    type: 'upload',
    rules: '{required: true}',
    section_id: sections[6].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    title: 'Upload Signature',
    title_ar: 'Upload Signature',
    type: 'upload',
    rules: '{required: true}',
    section_id: sections[6].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    title: 'Text1',
    title_ar: 'Text1',
    type: 'text',
    rules: '{required: true}',
    section_id: sections[7].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    title: 'Text2',
    title_ar: 'Text2',
    type: 'text',
    rules: '{required: true}',
    section_id: sections[7].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    title: 'Text3',
    title_ar: 'Text3',
    type: 'text',
    rules: '{required: true}',
    section_id: sections[7].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    title: 'Text4',
    title_ar: 'Text4',
    type: 'text',
    rules: '{required: true}',
    section_id: sections[7].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    title: 'Text5',
    title_ar: 'Text5',
    type: 'text',
    rules: '{required: true}',
    section_id: sections[7].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    title: 'Text1',
    title_ar: 'Text1',
    type: 'text',
    rules: '{required: true}',
    section_id: sections[8].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    title: 'Text2',
    title_ar: 'Text2',
    type: 'text',
    rules: '{required: true}',
    section_id: sections[8].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    title: 'Text3',
    title_ar: 'Text3',
    type: 'text',
    rules: '{required: true}',
    section_id: sections[8].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    title: 'Text4',
    title_ar: 'Text4',
    type: 'text',
    rules: '{required: true}',
    section_id: sections[8].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    title: 'Text5',
    title_ar: 'Text5',
    type: 'text',
    rules: '{required: true}',
    section_id: sections[8].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    title: 'Radio1',
    title_ar: 'Radio1',
    type: 'radiobutton',
    rules: '{required: true}',
    section_id: sections[9].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    title: 'Radio2',
    title_ar: 'Radio2',
    type: 'radiobutton',
    rules: '{required: true}',
    section_id: sections[9].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    title: 'Radio3',
    title_ar: 'Radio3',
    type: 'radiobutton',
    rules: '{required: true}',
    section_id: sections[9].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    title: 'Radio4',
    title_ar: 'Radio4',
    type: 'radiobutton',
    rules: '{required: true}',
    section_id: sections[9].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    title: 'Radio5',
    title_ar: 'Radio5',
    type: 'radiobutton',
    rules: '{required: true}',
    section_id: sections[9].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    title: 'Text1',
    title_ar: 'Text1',
    type: 'text',
    rules: '{required: true}',
    section_id: sections[10].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    title: 'Text2',
    title_ar: 'Text2',
    type: 'text',
    rules: '{required: true}',
    section_id: sections[10].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    title: 'Text3',
    title_ar: 'Text3',
    type: 'text',
    rules: '{required: true}',
    section_id: sections[10].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    title: 'Text4',
    title_ar: 'Text4',
    type: 'text',
    rules: '{required: true}',
    section_id: sections[10].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    title: 'Text5',
    title_ar: 'Text5',
    type: 'text',
    rules: '{required: true}',
    section_id: sections[10].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
];

const options: any[] = [
  {
    id: uuidV4(),
    name: 'Saving / Investment',
    name_ar: 'Saving / Investment',
    question_id: questions[0].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    name: 'Salary Transfer',
    name_ar: 'Salary Transfer',
    question_id: questions[0].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    name: 'Financing facility',
    name_ar: 'Financing facility',
    question_id: questions[0].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    name: 'Others',
    name_ar: 'Others',
    question_id: questions[0].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    name: 'High',
    name_ar: 'High',
    question_id: questions[1].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    name: 'Low',
    name_ar: 'Low',
    question_id: questions[1].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    name: 'High',
    name_ar: 'High',
    question_id: questions[2].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    name: 'Low',
    name_ar: 'Low',
    question_id: questions[2].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    name: 'High',
    name_ar: 'High',
    question_id: questions[3].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    name: 'Low',
    name_ar: 'Low',
    question_id: questions[3].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    name: 'High',
    name_ar: 'High',
    question_id: questions[4].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    name: 'Low',
    name_ar: 'Low',
    question_id: questions[4].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    name: 'High',
    name_ar: 'High',
    question_id: questions[5].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    name: 'Low',
    name_ar: 'Low',
    question_id: questions[5].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    name: 'High',
    name_ar: 'High',
    question_id: questions[6].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    name: 'Low',
    name_ar: 'Low',
    question_id: questions[6].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    name: 'High',
    name_ar: 'High',
    question_id: questions[7].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    name: 'Low',
    name_ar: 'Low',
    question_id: questions[7].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    name: 'Yes',
    name_ar: 'Yes',
    question_id: questions[8].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    name: 'No',
    name_ar: 'No',
    question_id: questions[8].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    name: 'Yes',
    name_ar: 'Yes',
    question_id: questions[9].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    name: 'No',
    name_ar: 'No',
    question_id: questions[9].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    name: 'Yes',
    name_ar: 'Yes',
    question_id: questions[10].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    name: 'No',
    name_ar: 'No',
    question_id: questions[10].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    name: 'Yes',
    name_ar: 'Yes',
    question_id: questions[11].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    name: 'No',
    name_ar: 'No',
    question_id: questions[11].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    name: 'Primary',
    name_ar: 'Primary',
    question_id: questions[12].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    name: 'Intermediary',
    name_ar: 'Intermediary',
    question_id: questions[12].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    name: 'Secondary',
    name_ar: 'Secondary',
    question_id: questions[12].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    name: 'Diplomatic Area',
    name_ar: 'Diplomatic Area',
    question_id: questions[12].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    name: 'Post Graduate',
    name_ar: 'Post Graduate',
    question_id: questions[12].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    name: 'Business',
    name_ar: 'Business',
    question_id: questions[13].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    name: 'Parents / Spouse',
    name_ar: 'Parents / Spouse',
    question_id: questions[13].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    name: 'Rental',
    name_ar: 'Rental',
    question_id: questions[13].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    name: 'Salary',
    name_ar: 'Salary',
    question_id: questions[13].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    name: 'Saving',
    name_ar: 'Saving',
    question_id: questions[13].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    name: 'Other',
    name_ar: 'Other',
    question_id: questions[13].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    name: 'Yes',
    name_ar: 'Yes',
    question_id: questions[14].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    name: 'No',
    name_ar: 'No',
    question_id: questions[14].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    name: 'Employed',
    name_ar: 'Employed',
    question_id: questions[16].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    name: 'House Wife',
    name_ar: 'House Wife',
    question_id: questions[16].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    name: 'Retired',
    name_ar: 'Retired',
    question_id: questions[16].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    name: 'Self-Employed',
    name_ar: 'Self-Employed',
    question_id: questions[16].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    name: 'Student',
    name_ar: 'Student',
    question_id: questions[16].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    name: 'Unemployed',
    name_ar: 'Unemployed',
    question_id: questions[16].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },

  {
    id: uuidV4(),
    name: 'Below BD 500',
    name_ar: 'Below BD 500',
    question_id: questions[18].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    name: 'BD 500 - BD 999',
    name_ar: 'BD 500 - BD 999',
    question_id: questions[18].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    name: 'BD 1,000 - BD 1,999',
    name_ar: 'BD 1,000 - BD 1,999',
    question_id: questions[18].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    name: 'BD 2,000 - BD 2,999',
    name_ar: 'BD 2,000 - BD 2,999',
    question_id: questions[18].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    name: 'BD 3,000 - BD 5,000',
    name_ar: 'BD 3,000 - BD 5,000',
    question_id: questions[18].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    name: 'Above 5,000',
    name_ar: 'Above 5,000',
    question_id: questions[18].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    name: 'Driving License',
    name_ar: 'Driving License',
    question_id: questions[26].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    name: 'Utility Bill',
    name_ar: 'Utility Bill',
    question_id: questions[26].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    name: 'Bank Statement',
    name_ar: 'Bank Statement',
    question_id: questions[26].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    name: 'Govt doc stating your address',
    name_ar: 'Govt doc stating your address',
    question_id: questions[26].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    name: 'I don’t have proof of address',
    name_ar: 'I don’t have proof of address',
    question_id: questions[26].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    name: 'A',
    name_ar: 'A',
    question_id: questions[39].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    name: 'B',
    name_ar: 'B',
    question_id: questions[39].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    name: 'C',
    name_ar: 'C',
    question_id: questions[39].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    name: 'A',
    name_ar: 'A',
    question_id: questions[40].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    name: 'B',
    name_ar: 'B',
    question_id: questions[40].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    name: 'C',
    name_ar: 'C',
    question_id: questions[40].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    name: 'A',
    name_ar: 'A',
    question_id: questions[41].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    name: 'B',
    name_ar: 'B',
    question_id: questions[41].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    name: 'C',
    name_ar: 'C',
    question_id: questions[41].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    name: 'A',
    name_ar: 'A',
    question_id: questions[42].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    name: 'B',
    name_ar: 'B',
    question_id: questions[42].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    name: 'C',
    name_ar: 'C',
    question_id: questions[42].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    name: 'A',
    name_ar: 'A',
    question_id: questions[43].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    name: 'B',
    name_ar: 'B',
    question_id: questions[43].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
  {
    id: uuidV4(),
    name: 'C',
    name_ar: 'C',
    question_id: questions[43].id,
    tenant_id: process.env.ENV_RBX_TENANT_ID,
  },
];

export async function seed(knex: Knex): Promise<any> {
  return processSeed(knex, false);
}

export async function processSeed(
  knex: Knex,
  generateSql = true,
): Promise<any> {
  const insertTemplates = () =>
    knex(TABLE.TEMPLATE).insert(
      templates.map(template => ({
        ...template,
        created_by: CREATED_BY.SYSTEM,
        updated_by: CREATED_BY.SYSTEM,
      })),
    );

  const insertSections = () =>
    knex(TABLE.SECTION).insert(
      sections.map(section => ({
        ...section,
        created_by: CREATED_BY.SYSTEM,
        updated_by: CREATED_BY.SYSTEM,
      })),
    );

  const insertQuestions = () =>
    knex(TABLE.QUESTION).insert(
      questions.map(question => ({
        ...question,
        created_by: CREATED_BY.SYSTEM,
        updated_by: CREATED_BY.SYSTEM,
      })),
    );

  const insertOptions = () =>
    knex(TABLE.OPTION).insert(
      options.map(option => ({
        ...option,
        created_by: CREATED_BY.SYSTEM,
        updated_by: CREATED_BY.SYSTEM,
      })),
    );

  if (generateSql) {
    let sql = '';
    sql += `${insertTemplates().toString()};\r\n\n`;
    sql += `${insertSections().toString()};\r\n\n`;
    sql += `${insertQuestions().toString()};\r\n\n`;
    sql += `${insertOptions().toString()};\r\n\n`;
    return sql;
  }

  return Promise.all([
    insertTemplates(),
    insertSections(),
    insertQuestions(),
    insertOptions(),
  ]);
}
