export const USER='/api/v1/user'
export const ROLE='/api/v1/role'
export const MODULE='/api/v1/module'
export const PERMISSION='/api/v1/permission'
export const ROLE_MODULE='/api/v1/role_module'
export const ROLE_MODULE_PERMISSION='/api/v1/role_module_permission'
export const ROLE_MODULE_BY_ID='/api/v1/getRoleModuleById'