export const SERVICES = {
  'api/v1/entitlements/auth': { channels: ['RUBIX-DEV-INT'] },
  'api/v1/entitlements/users': { channels: ['RUBIX-DEV-INT'] },
  'api/v1/entitlements/invitations': { channels: ['RUBIX-DEV-INT'] },
  'api/v1/entitlements/roles': { channels: ['RUBIX-DEV-INT'] },
  'api/v1/entitlements/modules': { channels: ['RUBIX-DEV-INT'] },
  'api/v1/entitlements/permissions': { channels: ['RUBIX-DEV-INT'] },
  'api/v1/entitlements/customers': { channels: ['RUBIX-DEV-INT'] },
  'api/v1/entitlements/working-days': { channels: ['RUBIX-DEV-INT'] },
  'api/v1/entitlements/holidays': { channels: ['RUBIX-DEV-INT'] },
  'api/v1/entitlements/leave-types': { channels: ['RUBIX-DEV-INT'] },
  'api/v1/entitlements/leaves': { channels: ['RUBIX-DEV-INT'] },
  // 'api/v1/onboarding/auth': { channels: ['RUBIX-DEV-INT'] },
  // 'api/v1/onboarding/sessions': { channels: ['RUBIX-DEV-INT'] },
  // 'api/v1/onboarding/evaluations': { channels: ['RUBIX-DEV-INT'] },
  // 'api/v1/onboarding/faces': { channels: ['RUBIX-DEV-INT'] },
  // 'api/v1/onboarding/attachments': { channels: ['RUBIX-DEV-INT'] },
  // 'api/v1/onboarding/documents': { channels: ['RUBIX-DEV-INT'] },
  // 'api/v1/onboarding/otp': { channels: ['RUBIX-DEV-INT'] },
  // 'api/v1/onboarding/compliance': { channels: ['RUBIX-DEV-INT'] },
  // 'api/v1/onboarding/callback': { channels: ['RUBIX-DEV-INT'] },
  // 'api/v1/onboarding/agents': { channels: ['RUBIX-DEV-INT'] },
  // 'api/v1/onboarding/aml': { channels: ['RUBIX-DEV-INT'] },
  // 'api/v1/onboarding/appointments': { channels: ['RUBIX-DEV-INT'] },
  // 'api/v1/references/countries': { channels: ['RUBIX-DEV-INT'] },
  // 'api/v1/references/currencies': { channels: ['RUBIX-DEV-INT'] },
};

export const GQL_SERVICES = [
  {
    name: 'Notification Service',
    host_name: 'retail_notification',
    port: 5030,
    version: '1.0',
    context: '/graphql',
    is_secure: false,
  },
  {
    name: 'User Management Service',
    host_name: 'retail_user_management',
    port: 5020,
    version: '1.0',
    context: '/graphql',
    is_secure: false,
  },
  {
    name: 'Compliance Service',
    host_name: 'retail_compliance',
    port: 5010,
    version: '1.0',
    context: '/graphql',
    is_secure: false,
  },
  {
    name: 'Identity Service',
    host_name: 'retail_identity',
    port: 4010,
    version: '1.0',
    context: '/graphql',
    is_secure: false,
  },
];
