import { URI } from '@shared/constants/app.constants';
import { Injectable } from '@angular/core';
import { Observable, of, BehaviorSubject } from 'rxjs';
import { RetailNetworkService } from '@shared/services/network/retail-network.service';
import { environment } from '../../../../environments/environment';
import { InternationalTransferRequest } from '../models/transfer-request.model';
import { tap } from 'rxjs/operators';

@Injectable({
    providedIn: 'root',
})
export class InternationalTransferRequestsService {
    approve(obj) {
        this._RetailNetworkService.post(environment.API_BASE_URL, `${URI.APPROVE_BANK_TRANSACTION}`, obj);
    }
    
    reject(obj: any) {
        this._RetailNetworkService.post(environment.API_BASE_URL, `${URI.REJECT_BANK_TRANSACTION}`, obj);
    }

    constructor(private _RetailNetworkService: RetailNetworkService) {
        this.transferRequestList = new BehaviorSubject<InternationalTransferRequest[]>([]);
    }

    transferRequestList: BehaviorSubject<InternationalTransferRequest[]>;

    getAll(params?: any): Observable<any> {
        this.transferRequestList.next(transferRequestGetAll.data.records);
        //const res = of(transferRequestGetAll);
        const res = this._RetailNetworkService.getAll(environment.API_BASE_URL, `${URI.INTERNATIONAL_TRANSFER_REQUEST}`, params);
        res.pipe(tap(res => {
            this.transferRequestList.next(res);
        }));
        return res;
    }

}

export const transferRequestGetAll: any = {
    "data": {
        "records": [
            {
                "id": "0059a1dd-b618-44d6-81c8-46b6aa2cf36b",
                "customer_id": "e90ecd6e-8d0c-4f5e-9518-687af4110438",
                "customer_name": "FAISAL SAEED AHMED MO ALZAMAN",
                "from_rim_no": "132910",
                "from_account_id": "602000221039",
                "from_currency_id": "BHD",
                "from_iban": "BH42KFHO00602000221039",
                "from_full_name": "FAISAL SAEED AHMED MO ALZAMAN",
                "from_country_code": "BH",
                "from_bank_code": "KFHO",
                "amount": 9300,
                "ex_rate": 1,
                "local_eq": 9300,
                "description": "Bgfbjj",
                "system_date_time": "2020-06-30T16:05:34.000Z",
                "status": "P",
                "beneficiary_id": "cf663a28-078f-4d5a-8c06-4f75e8c23a13",
                "to_account_id": "GB33CHAS60924267102507",
                "to_currency_id": "USD",
                "to_iban": "GB33CHAS60924267102507",
                "to_full_name": "Faisal",
                "to_country_code": "GB",
                "to_bank_code": "CHAS",
                "bank_charges": "Our",
                "authorize_by": "NULL",
                "authorize_time": null,
                "authorize_terminal": "NULL",
                "bank_trx_ref_no": "REF-234#",
                "created_on": null,
                "created_by": null,
                "updated_on": null,
                "updated_by": null
            },
            {
                "id": "03380c10-cbf0-4e4f-a033-91b1625b5e05",
                "customer_id": "1322489c-938b-4610-be6e-7b47c763d9e8",
                "customer_name": "MASHAEL ALI MOHAMEDALHASHEMI",
                "from_rim_no": "139203",
                "from_account_id": "602000310910",
                "from_currency_id": "BHD",
                "from_iban": "BH77KFHO00602000310910",
                "from_full_name": "MASHAEL ALI MOHAMEDALHASHEMI",
                "from_country_code": "BH",
                "from_bank_code": "KFHO",
                "amount": 5,
                "ex_rate": 1,
                "local_eq": 5,
                "description": "yyrhrjjrj|DLL",
                "system_date_time": "2021-03-16T03:25:14.000Z",
                "status": "P",
                "beneficiary_id": "441c4974-eeb1-4d4f-a69a-568e3357f6bf",
                "to_account_id": "AE850260000959024729001",
                "to_currency_id": "BHD",
                "to_iban": "AE850260000959024729001",
                "to_full_name": "farhan nizar",
                "to_country_code": "AE",
                "to_bank_code": "26",
                "bank_charges": "Shared",
                "authorize_by": "NULL",
                "authorize_time": null,
                "authorize_terminal": "NULL",
                "bank_trx_ref_no": "REF@1234",
                "created_on": null,
                "created_by": null,
                "updated_on": null,
                "updated_by": null
            },
            {
                "id": "066272bb-efb1-4d25-a98c-90bdb5ad9614",
                "customer_id": "d5b9a155-4df4-4819-92e2-ccd953003b4f",
                "customer_name": "MASHAELALHASHEMI",
                "from_rim_no": "139157",
                "from_account_id": "602000310538",
                "from_currency_id": "BHD",
                "from_iban": "BH33KFHO00602000310538",
                "from_full_name": "MASHAELALHASHEMI",
                "from_country_code": "BH",
                "from_bank_code": "KFHO",
                "amount": 0.1,
                "ex_rate": 1,
                "local_eq": 0.1,
                "description": "hhhhh",
                "system_date_time": "2021-02-10T16:11:02.000Z",
                "status": "P",
                "beneficiary_id": "4e1514dc-9646-49e9-b58e-206b34bc2107",
                "to_account_id": "GB94BARC10201530093459",
                "to_currency_id": "BHD",
                "to_iban": "GB94BARC10201530093459",
                "to_full_name": "international ",
                "to_country_code": "GB",
                "to_bank_code": "BARC",
                "bank_charges": "Shared",
                "authorize_by": "NULL",
                "authorize_time": null,
                "authorize_terminal": "NULL",
                "bank_trx_ref_no": "REF@1234",
                "created_on": null,
                "created_by": null,
                "updated_on": null,
                "updated_by": null
            },
            {
                "id": "07d8c1b1-0f45-43db-993b-856bcd54b93c",
                "customer_id": "e90ecd6e-8d0c-4f5e-9518-687af4110438",
                "customer_name": "FAISAL SAEED AHMED MO ALZAMAN",
                "from_rim_no": "132910",
                "from_account_id": "602000221039",
                "from_currency_id": "BHD",
                "from_iban": "BH42KFHO00602000221039",
                "from_full_name": "FAISAL SAEED AHMED MO ALZAMAN",
                "from_country_code": "BH",
                "from_bank_code": "KFHO",
                "amount": 2000,
                "ex_rate": 1,
                "local_eq": 2000,
                "description": "Inbetsment",
                "system_date_time": "2020-06-30T16:20:26.000Z",
                "status": "P",
                "beneficiary_id": "cf663a28-078f-4d5a-8c06-4f75e8c23a13",
                "to_account_id": "GB33CHAS60924267102507",
                "to_currency_id": "USD",
                "to_iban": "GB33CHAS60924267102507",
                "to_full_name": "Faisal",
                "to_country_code": "GB",
                "to_bank_code": "CHAS",
                "bank_charges": "Our",
                "authorize_by": "NULL",
                "authorize_time": null,
                "authorize_terminal": "NULL",
                "bank_trx_ref_no": "REF@1234",
                "created_on": null,
                "created_by": null,
                "updated_on": null,
                "updated_by": null
            },
            {
                "id": "07e67bad-b4e5-40d4-8982-7a145d900cf1",
                "customer_id": "02dab17b-da20-4822-9649-5aee68e18c9a",
                "customer_name": "HAWRA SAYED SHUBBER MEBRAHIM",
                "from_rim_no": "139218",
                "from_account_id": "602000311038",
                "from_currency_id": "BHD",
                "from_iban": "BH16KFHO00602000311038",
                "from_full_name": "HAWRA SAYED SHUBBER MEBRAHIM",
                "from_country_code": "BH",
                "from_bank_code": "KFHO",
                "amount": 5,
                "ex_rate": 1,
                "local_eq": 5,
                "description": "|PPA",
                "system_date_time": "2021-03-16T09:25:03.000Z",
                "status": "P",
                "beneficiary_id": "3e8925ed-f659-497b-b925-6da6d3a4d14e",
                "to_account_id": "AT271953000100011911",
                "to_currency_id": "BHD",
                "to_iban": "AT271953000100011911",
                "to_full_name": "yaser",
                "to_country_code": "AT",
                "to_bank_code": "19530",
                "bank_charges": "Shared",
                "authorize_by": "NULL",
                "authorize_time": null,
                "authorize_terminal": "NULL",
                "bank_trx_ref_no": "REF@1234",
                "created_on": null,
                "created_by": null,
                "updated_on": null,
                "updated_by": null
            },
            {
                "id": "0b418df4-21f0-49d1-adbf-205a0f27657c",
                "customer_id": "cbf7cbc7-c099-45d2-b8c3-49d5b86a0c2f",
                "customer_name": "Ashar Masood Nazim",
                "from_rim_no": "107244",
                "from_account_id": "602000000741",
                "from_currency_id": "BHD",
                "from_iban": "BH48KFHO00602000000741",
                "from_full_name": "Ashar Masood Nazim",
                "from_country_code": "BH",
                "from_bank_code": "KFHO",
                "amount": 2,
                "ex_rate": 1,
                "local_eq": 2,
                "description": "Test",
                "system_date_time": "2019-06-09T11:17:13.000Z",
                "status": "P",
                "beneficiary_id": "3df3ce00-4665-43b1-a378-0d5dc7f54abb",
                "to_account_id": "PK05ALFH5518005000952179",
                "to_currency_id": "BHD",
                "to_iban": "PK05ALFH5518005000952179",
                "to_full_name": "Ali",
                "to_country_code": "PK",
                "to_bank_code": "ALFH",
                "bank_charges": "OUR",
                "authorize_by": "NULL",
                "authorize_time": null,
                "authorize_terminal": "NULL",
                "bank_trx_ref_no": "REF@1234",
                "created_on": null,
                "created_by": null,
                "updated_on": null,
                "updated_by": null
            },
            {
                "id": "0c654556-c432-00e0-d539-a07699bb9b27",
                "customer_id": "8B6E0CC7-13EB-4426-A4CB-01E3873352AD",
                "customer_name": "MASHAELALHASHEMI",
                "from_rim_no": "139176",
                "from_account_id": "00602000310910",
                "from_currency_id": "BHD",
                "from_iban": "BH77KFHO00602000310910",
                "from_full_name": "MASHAELALHASHEMI",
                "from_country_code": "BH",
                "from_bank_code": "KFHO",
                "amount": 400,
                "ex_rate": 1,
                "local_eq": 400,
                "description": "loan payment",
                "system_date_time": "2021-06-23T21:42:40.000Z",
                "status": "P",
                "beneficiary_id": "000b6987-4182-4086-9718-6e340c9752fd",
                "to_account_id": "30093459",
                "to_currency_id": "GBP",
                "to_iban": "GB94BARC10201530093459",
                "to_full_name": "MASHAELALHASHEMI",
                "to_country_code": "GB",
                "to_bank_code": "BARC",
                "bank_charges": "400",
                "authorize_by": null,
                "authorize_time": null,
                "authorize_terminal": null,
                "bank_trx_ref_no": "GA800750000063742901",
                "created_on": "2021-06-23T16:42:40.843Z",
                "created_by": "api",
                "updated_on": null,
                "updated_by": null
            },
            {
                "id": "0d33445d-43da-424b-8f9b-ca76c239f912",
                "customer_id": "1322489c-938b-4610-be6e-7b47c763d9e8",
                "customer_name": "MASHAEL ALI MOHAMEDALHASHEMI",
                "from_rim_no": "139203",
                "from_account_id": "602000310910",
                "from_currency_id": "BHD",
                "from_iban": "BH77KFHO00602000310910",
                "from_full_name": "MASHAEL ALI MOHAMEDALHASHEMI",
                "from_country_code": "BH",
                "from_bank_code": "KFHO",
                "amount": 21.6,
                "ex_rate": 1,
                "local_eq": 21.6,
                "description": "needed",
                "system_date_time": "2021-03-07T02:51:04.000Z",
                "status": "P",
                "beneficiary_id": "441c4974-eeb1-4d4f-a69a-568e3357f6bf",
                "to_account_id": "AE850260000959024729001",
                "to_currency_id": "BHD",
                "to_iban": "AE850260000959024729001",
                "to_full_name": "farhan nizar",
                "to_country_code": "AE",
                "to_bank_code": "26",
                "bank_charges": "Shared",
                "authorize_by": "NULL",
                "authorize_time": null,
                "authorize_terminal": "NULL",
                "bank_trx_ref_no": "REF@1234",
                "created_on": null,
                "created_by": null,
                "updated_on": null,
                "updated_by": null
            },
            {
                "id": "0d984044-088a-4452-aecc-8211603e144f",
                "customer_id": "b6b2e42d-801d-418f-8af6-af2b0dbce8ea",
                "customer_name": "FATEMA AHMED MAHDIZAINUDDIN",
                "from_rim_no": "139216",
                "from_account_id": "602000311003",
                "from_currency_id": "BHD",
                "from_iban": "BH88KFHO00602000311003",
                "from_full_name": "FATEMA AHMED MAHDIZAINUDDIN",
                "from_country_code": "BH",
                "from_bank_code": "KFHO",
                "amount": 1055,
                "ex_rate": 1,
                "local_eq": 1055,
                "description": "needed",
                "system_date_time": "2021-03-04T06:29:14.000Z",
                "status": "P",
                "beneficiary_id": "31ad88d1-3fb3-4869-ba23-d32786d6999e",
                "to_account_id": "GB94BARC10201530093459",
                "to_currency_id": "BHD",
                "to_iban": "GB94BARC10201530093459",
                "to_full_name": "intern",
                "to_country_code": "GB",
                "to_bank_code": "BARC",
                "bank_charges": "Shared",
                "authorize_by": "NULL",
                "authorize_time": null,
                "authorize_terminal": "NULL",
                "bank_trx_ref_no": null,
                "created_on": null,
                "created_by": null,
                "updated_on": null,
                "updated_by": null
            },
            {
                "id": "1185763d-9940-4e91-ab0a-df430de648fd",
                "customer_id": "1322489c-938b-4610-be6e-7b47c763d9e8",
                "customer_name": "MASHAEL ALI MOHAMEDALHASHEMI",
                "from_rim_no": "139203",
                "from_account_id": "602000310910",
                "from_currency_id": "BHD",
                "from_iban": "BH77KFHO00602000310910",
                "from_full_name": "MASHAEL ALI MOHAMEDALHASHEMI",
                "from_country_code": "BH",
                "from_bank_code": "KFHO",
                "amount": 1,
                "ex_rate": 1,
                "local_eq": 1,
                "description": "asas",
                "system_date_time": "2021-03-04T15:58:06.000Z",
                "status": "P",
                "beneficiary_id": "441c4974-eeb1-4d4f-a69a-568e3357f6bf",
                "to_account_id": "AE850260000959024729001",
                "to_currency_id": "BHD",
                "to_iban": "AE850260000959024729001",
                "to_full_name": "farhan nizar",
                "to_country_code": "AE",
                "to_bank_code": "26",
                "bank_charges": "Shared",
                "authorize_by": "NULL",
                "authorize_time": null,
                "authorize_terminal": "NULL",
                "bank_trx_ref_no": null,
                "created_on": null,
                "created_by": null,
                "updated_on": null,
                "updated_by": null
            }
        ],
        "recordCount": 103,
        "startIndex": null,
        "endIndex": null,
        "totalPages": 11,
        "pageSize": 10,
        "currentPage": null
    },
    "status": "true",
    "message": "success"
}