export const TABLE = {
  TEMPLATE: 'CMP_TEMPLATE',
  QUESTION: 'CMP_QUESTION',
  SECTION: 'CMP_SECTION',
  OPTION: 'CMP_OPTION',
  TEMPLATE_QUESTIONS: 'CMP_TEMPLATE_QUESTIONS',
  TEMPLATE_RESPONSE: 'CMP_TEMPLATE_RESPONSES',
};
export const DATABASE_MIGRATION_TABLE_NAME = 'rubix_migrations';
export const DATABASE_MIGRATION_DIRECTORY = 'src/core/database/migrations';
export const DATABASE_SEED_DIRECTORY = 'src/core/database/seeds';
