export const TABLE = {
  SESSION: 'IDT_SESSION',
  DOCUMENT_TYPE: 'IDT_DOCUMENT_TYPE',
  CUSTOMER: 'IDT_CUSTOMER',
  POST: 'T_POST',
  COMMENT: 'T_COMMENT',
};

export const DATABASE_UUID_METHOD = 'NEWID()';
export const DATABASE_MIGRATION_TABLE_NAME = 'RUBIX_IDENTITY_MIGRATIONS';
export const DATABASE_MIGRATION_DIRECTORY = 'src/core/database/migrations';
export const DATABASE_SEED_DIRECTORY = 'src/core/database/seeds';
export const DOCUMENT_TYPES = [
  'SELFIE',
  'LIVENESS',
  'PASSPORT',
  'DRIVING_LICENSE',
  'NATIONAL_ID_FRONT_SIDE',
  'NATIONAL_ID_BACK_SIDE',
];

export const CUSTOMER_STATUSES = {
 PENDING: 'PENDING',
 COMPLETED: 'COMPLETED'
}
