version: "3.7"
services:
  jazeel:
    image: aioncontainer.azurecr.io/jazeel_webadmin:1.0
    container_name: jazeel_webadmin
    networks:
      - jazeel
    restart: unless-stopped
    build: .
    environment:
      - NODE_ENV=production
      - ENV_RBX_APP_SECRETE=abfFGHIepqrstuvwSTUCDEXYZ
      - ENV_RBX_RETAIL_API_BASE_URL=https://rubix-dev01.conduit-aiondigital.com
      - ENV_RBX_API_BASE_URL=https://aionj2middlewaredev.uksouth.cloudapp.azure.com
      - ENV_RBX_CHANNEL_ID=RUBIX-DEV-INT
      - ENV_RBX_TENANT_ID=9013C327-1190-4875-A92A-83ACA9029160
networks:
  jazeel:
    name: jazeel
