version: "3.2"

services:
  #=================================================================
  # Gateway Service
  #=================================================================
  gateway-servcie:
    build:
      context: ../../../retail/middleware/gateway.service
      dockerfile: Dockerfile
    image: "gateway-service:v1"
    container_name: gateway_service
    environment:
      - ENV_RBX_NGINX_SERVER_NAME=localhost
      - ENV_RBX_PORTAL_HOST=192.168.18.64
      - ENV_RBX_PORTAL_PORT=3000
      - ENV_RBX_ENTITLEMENT_HOST=entitlement_business_service
      - ENV_RBX_ENTITLEMENT_PORT=5000
      - ENV_RBX_ONBOARDING_HOST=onboarding_business_service
      - ENV_RBX_ONBOARDING_PORT=4000
      - ENV_RBX_NGINX_MAX_BODY=100M
    networks:
      - rubix-middleware-network
    ports:
      - 80:80

  #=================================================================
  # Admin Web Portal Service
  #=================================================================
  # webportal-service:
  #   build:
  #     context: ../../../retail/webadmin/
  #     dockerfile: Dockerfile
  #   image: "webportal:v1"
  #   container_name: "webportal_service"
  #   environment:
  #     - ENV_CDT_API_BASE_URL=http://192.168.18.64:4000
  #   restart: always
  #   networks:
  #     - rubix-middleware-network
  #   ports:
  #     - 3000:3000
  #=================================================================
  # Entitlement Business Service
  #=================================================================
  entitlement-business-service:
    build:
      context: ../../../retail/middleware/entitlement.business.service
      dockerfile: Dockerfile
    image: "entitlement-business-service:v1"
    container_name: "entitlement_business_service"
    environment:
      - ENV_RBX_PORT=5000
      - ENV_RBX_APP_NAME=Rubix | Entitlement Business Service
      - ENV_RBX_SWAGGER_ENABLED=true
      - ENV_RBX_API_URL_PREFIX=api/v1/entitlements/
    restart: always
    networks:
      - rubix-middleware-network
    ports:
      - 5000:5000

  #=================================================================
  # Onboarding Business Service
  #=================================================================
  onboarding-business-service:
    build:
      context: ../../../retail/middleware/onboarding.business.service
      dockerfile: Dockerfile
    image: "onboarding-business-service:v1"
    container_name: "onboarding_business_service"
    environment:
      - ENV_RBX_PORT=4000
      - ENV_RBX_APP_NAME=Rubix Onboarding Business Service
      - ENV_RBX_SWAGGER_ENABLED=true
      - ENV_RBX_API_URL_PREFIX=api/v1/onboarding/
    restart: always
    networks:
      - rubix-middleware-network
    ports:
      - 4000:4000

  #=================================================================
  # Template Service
  #=================================================================
  template-service:
    build:
      context: ../../../retail/middleware/template.service
      dockerfile: Dockerfile
    image: "template-service:v1"
    container_name: "template_service"
    environment:
      - ENV_RBX_PORT=5010
      - ENV_RBX_DB_USERNAME=$ENV_RBX_DB_USERNAME
      - ENV_RBX_DB_PASS=$ENV_RBX_DB_PASS
      - ENV_RBX_DB_NAME=$ENV_RBX_DB_NAME
      - ENV_RBX_DB_HOST=$ENV_RBX_DB_HOST
      - ENV_RBX_DB_PORT=$ENV_RBX_DB_PORT
      - ENV_RBX_DB_TIMEOUT=$ENV_RBX_DB_TIMEOUT
      - ENV_RBX_DB_DIALECT=$ENV_RBX_DB_DIALECT
      - ENV_RBX_DB_DEBUG=$ENV_RBX_DB_DEBUG
      - ENV_RBX_GRAPHQL_DEBUG=$ENV_RBX_GRAPHQL_DEBUG
      - ENV_RBX_GRAPHQL_PLAYGROUND=$ENV_RBX_GRAPHQL_PLAYGROUND
    restart: always
    networks:
      - rubix-middleware-network
    ports:
      - 5010:5010

networks:
  rubix-middleware-network:
    driver: bridge