version: "3.2"

services:
  #=================================================================
  # Gateway Service
  #=================================================================
  gateway-servcie:
    build:
      context: ../../../retail/middleware/gateway.service
      dockerfile: Dockerfile
    image: "gateway-service:v1"
    container_name: gateway_service
    environment:
      - ENV_RBX_NGINX_SERVER_NAME=$ENV_RBX_NGINX_SERVER_NAME
      - ENV_RBX_PORTAL_HOST=$ENV_RBX_PORTAL_HOST
      - ENV_RBX_PORTAL_PORT=$ENV_RBX_PORTAL_PORT
      - ENV_RBX_ENTITLEMENT_HOST=$ENV_RBX_ENTITLEMENT_HOST
      - ENV_RBX_ENTITLEMENT_PORT=$ENV_RBX_ENTITLEMENT_PORT
      - ENV_RBX_ONBOARDING_HOST=$ENV_RBX_ONBOARDING_HOST
      - ENV_RBX_ONBOARDING_PORT=$ENV_RBX_ONBOARDING_PORT
      - ENV_RBX_NGINX_MAX_BODY=$ENV_RBX_NGINX_MAX_BODY
    networks:
      - rubix-middleware-network
    ports:
      - 80:80

  #=================================================================
  # Admin Web Portal Service
  #=================================================================
  webportal-service:
    build:
      context: ../../../retail/webadmin/
      dockerfile: Dockerfile
    image: "webportal:v1"
    container_name: "webportal_service"
    environment:
      - ENV_CDT_API_BASE_URL=$ENV_CDT_API_BASE_URL
    restart: always
    networks:
      - rubix-middleware-network
    ports:
      - 3000:4200
  #=================================================================
  # Entitlement Business Service
  #=================================================================
  entitlement-business-service:
    build:
      context: ../../../retail/middleware/entitlement.business.service
      dockerfile: Dockerfile
    image: "entitlement-business-service:v1"
    container_name: "entitlement_business_service"
    environment:
      - ENV_RBX_PORT=5000
      - ENV_RBX_APP_NAME=Rubix | Entitlement Business Service
      - ENV_RBX_SWAGGER_ENABLED=true
      - ENV_RBX_API_URL_PREFIX=api/v1/entitlements
      - ENV_RBX_CORS_ORIGIN=$ENV_RBX_CORS_ORIGIN
      - ENV_RBX_JWT_EXPIRY_IN_MINUTES=$ENV_RBX_JWT_EXPIRY_IN_MINUTES
      - ENV_RBX_JWT_SECRET=$ENV_RBX_JWT_SECRET
      - ENV_RBX_JWT_ALGORITHM=$ENV_RBX_JWT_ALGORITHM
    restart: always
    networks:
      - rubix-middleware-network
    ports:
      - 5000:5000

  #=================================================================
  # Onboarding Business Service
  #=================================================================
  onboarding-business-service:
    build:
      context: ../../../retail/middleware/onboarding.business.service
      dockerfile: Dockerfile
    image: "onboarding-business-service:v1"
    container_name: "onboarding_business_service"
    environment:
      - ENV_RBX_PORT=4000
      - ENV_RBX_APP_NAME=Rubix Onboarding Business Service
      - ENV_RBX_SWAGGER_ENABLED=true
      - ENV_RBX_API_URL_PREFIX=api/v1/onboarding/
    restart: always
    networks:
      - rubix-middleware-network
    ports:
      - 4000:4000

  #=================================================================
  # Template Service
  #=================================================================
  template-service:
    build:
      context: ../../../retail/middleware/template.service
      dockerfile: Dockerfile
    image: "template-service:v1"
    container_name: "template_service"
    environment:
      - ENV_RBX_PORT=5010
      - ENV_RBX_DB_USERNAME=$ENV_RBX_DB_USERNAME
      - ENV_RBX_DB_PASS=$ENV_RBX_DB_PASS
      - ENV_RBX_DB_NAME=$ENV_RBX_DB_NAME
      - ENV_RBX_DB_HOST=$ENV_RBX_DB_HOST
      - ENV_RBX_DB_PORT=$ENV_RBX_DB_PORT
      - ENV_RBX_DB_TIMEOUT=$ENV_RBX_DB_TIMEOUT
      - ENV_RBX_DB_DIALECT=$ENV_RBX_DB_DIALECT
      - ENV_RBX_DB_DEBUG=$ENV_RBX_DB_DEBUG
      - ENV_RBX_GRAPHQL_DEBUG=$ENV_RBX_GRAPHQL_DEBUG
      - ENV_RBX_GRAPHQL_PLAYGROUND=$ENV_RBX_GRAPHQL_PLAYGROUND
    restart: always
    networks:
      - rubix-middleware-network
    ports:
      - 5010:5010

  #=================================================================
  # User Management Service
  #=================================================================
  user-management-service:
    build:
      context: ../../../retail/middleware/entitlement.service
      dockerfile: Dockerfile
    image: "user-management-service:v1"
    container_name: "user_management_service"
    environment:
      - ENV_RBX_PORT=5020
      - ENV_RBX_DB_USERNAME=$ENV_RBX_DB_USERNAME
      - ENV_RBX_DB_PASS=$ENV_RBX_DB_PASS
      - ENV_RBX_DB_NAME=$ENV_RBX_DB_NAME
      - ENV_RBX_DB_HOST=$ENV_RBX_DB_HOST
      - ENV_RBX_DB_PORT=$ENV_RBX_DB_PORT
      - ENV_RBX_DB_TIMEOUT=$ENV_RBX_DB_TIMEOUT
      - ENV_RBX_DB_DIALECT=$ENV_RBX_DB_DIALECT
      - ENV_RBX_DB_DEBUG=$ENV_RBX_DB_DEBUG
      - ENV_RBX_GRAPHQL_DEBUG=$ENV_RBX_GRAPHQL_DEBUG
      - ENV_RBX_GRAPHQL_PLAYGROUND=$ENV_RBX_GRAPHQL_PLAYGROUND
    restart: always
    networks:
      - rubix-middleware-network
    ports:
      - 5020:5020
  #=================================================================
  # Notification Service
  #=================================================================
  notification-service:
    build:
      context: ../../../retail/middleware/notifications
      dockerfile: Dockerfile
    image: "notification-service:v1"
    container_name: "unotification_service"
    environment:
      - ENV_RBX_PORT=5030
      - ENV_RBX_DB_USERNAME=$ENV_RBX_DB_USERNAME
      - ENV_RBX_DB_PASS=$ENV_RBX_DB_PASS
      - ENV_RBX_DB_NAME=$ENV_RBX_DB_NAME
      - ENV_RBX_DB_HOST=$ENV_RBX_DB_HOST
      - ENV_RBX_DB_PORT=$ENV_RBX_DB_PORT
      - ENV_RBX_DB_TIMEOUT=$ENV_RBX_DB_TIMEOUT
      - ENV_RBX_DB_DIALECT=$ENV_RBX_DB_DIALECT
      - ENV_RBX_DB_DEBUG=$ENV_RBX_DB_DEBUG
      - ENV_RBX_GRAPHQL_DEBUG=$ENV_RBX_GRAPHQL_DEBUG
      - ENV_RBX_GRAPHQL_PLAYGROUND=$ENV_RBX_GRAPHQL_PLAYGROUND
      - ENV_RBX_SMTP_HOST=$ENV_RBX_SMTP_HOST
      - ENV_RBX_SMTP_PORT=$ENV_RBX_SMTP_PORT
      - ENV_RBX_SMTP_IGNORETLS=$ENV_RBX_SMTP_IGNORETLS
      - ENV_RBX_SMTP_SECURE=$ENV_RBX_SMTP_SECURE
      - ENV_RBX_SMTP_USER=$ENV_RBX_SMTP_USER
      - ENV_RBX_SMTP_PASS=$ENV_RBX_SMTP_PASS
      - ENV_RBX_SMTP_SENDING_NAME=$ENV_RBX_SMTP_SENDING_NAME
      - ENV_RBX_SMTP_SENDING_EMAIL=$ENV_RBX_SMTP_SENDING_EMAIL
    restart: always
    networks:
      - rubix-middleware-network
    ports:
      - 5030:5030
networks:
  rubix-middleware-network:
    driver: bridge
