version: "3.2"

services:
  #=================================================================
  # Redis Server
  #=================================================================
  redis-server:
    image: redis:alpine
    container_name: cache
    networks:
      - core_service_network
  #=================================================================
  # Gateway Service
  #=================================================================
  gateway-servcie:
    build:
      context: ../../../retail/middleware/gateway.service
      dockerfile: Dockerfile
    image: "gateway-service:v1"
    container_name: gateway_service
    environment:
      - ENV_RBX_NGINX_SERVER_NAME=$ENV_RBX_NGINX_SERVER_NAME
      - ENV_RBX_PORTAL_HOST=$ENV_RBX_PORTAL_HOST
      - ENV_RBX_PORTAL_PORT=$ENV_RBX_PORTAL_PORT
      - ENV_RBX_ENTITLEMENT_HOST=$ENV_RBX_ENTITLEMENT_HOST
      - ENV_RBX_ENTITLEMENT_PORT=$ENV_RBX_ENTITLEMENT_PORT
      - ENV_RBX_ONBOARDING_HOST=$ENV_RBX_ONBOARDING_HOST
      - ENV_RBX_ONBOARDING_PORT=$ENV_RBX_ONBOARDING_PORT
      - ENV_RBX_NGINX_MAX_BODY=$ENV_RBX_NGINX_MAX_BODY
    networks:
      - core_service_network
    ports:
      - 80:80

  #=================================================================
  # Admin Web Portal Service
  #=================================================================
  webportal-service:
    build:
      context: ../../../retail/webadmin/
      dockerfile: Dockerfile
    image: "webportal:v1"
    container_name: "webportal_service"
    environment:
      - ENV_RBX_API_BASE_URL=$ENV_RBX_API_BASE_URL
      - ENV_RBX_APP_SECRET=$ENV_RBX_APP_SECRET
    restart: always
    networks:
      - core_service_network
    ports:
      - 3000:4200
  #=================================================================
  # Entitlement Business Service
  #=================================================================
  entitlement-business-service:
    build:
      context: ../../../retail/middleware/entitlement.business.service
      dockerfile: Dockerfile
    image: "entitlement-business-service:v1"
    container_name: "entitlement_business_service"
    environment:
      - ENV_RBX_PORT=5000
      - ENV_RBX_APP_NAME=Rubix | Entitlement Business Service
      - ENV_RBX_SWAGGER_ENABLED=true
      - ENV_RBX_API_URL_PREFIX=api/v1/entitlements
      - ENV_RBX_CORS_ORIGIN=$ENV_RBX_CORS_ORIGIN
      - ENV_RBX_CORS_ENABLED=$ENV_RBX_CORS_ENABLED
      - ENV_RBX_JWT_EXPIRY_MINUTES=$ENV_RBX_JWT_EXPIRY_MINUTES
      - ENV_RBX_JWT_REFRESH_EXPIRY_DAYS=$ENV_RBX_JWT_REFRESH_EXPIRY_DAYS
      - ENV_RBX_JWT_SECRET=$ENV_RBX_JWT_SECRET
      - ENV_RBX_JWT_REFRESH_SECRET=$ENV_RBX_JWT_REFRESH_SECRET
      - ENV_RBX_JWT_ALGORITHM=$ENV_RBX_JWT_ALGORITHM
      - ENV_RBX_WEB_ONBOARDING_LINK=$ENV_RBX_WEB_ONBOARDING_LINK
      - ENV_RBX_WEB_RESET_PASSWORD_LINK=$ENV_RBX_WEB_RESET_PASSWORD_LINK
      - ENV_RBX_REDIS_URL=$ENV_RBX_REDIS_URL
    restart: always
    networks:
      - core_service_network

  #=================================================================
  # Onboarding Business Service
  #=================================================================
  onboarding-business-service:
    build:
      context: ../../../retail/middleware/onboarding.business.service
      dockerfile: Dockerfile
    image: "onboarding-business-service:v1"
    container_name: "onboarding_business_service"
    environment:
      - ENV_RBX_PORT=4000
      - ENV_RBX_APP_NAME=Rubix | Onboarding Business Service
      - ENV_RBX_SWAGGER_ENABLED=true
      - ENV_RBX_API_URL_PREFIX=api/v1/onboarding
      - ENV_RBX_CORS_ORIGIN=$ENV_RBX_CORS_ORIGIN
      - ENV_RBX_CORS_ENABLED=$ENV_RBX_CORS_ENABLED
      - ENV_RBX_JWT_EXPIRY_MINUTES=$ENV_RBX_JWT_EXPIRY_MINUTES
      - ENV_RBX_JWT_REFRESH_EXPIRY_DAYS=$ENV_RBX_JWT_REFRESH_EXPIRY_DAYS
      - ENV_RBX_JWT_SECRET=$ENV_RBX_JWT_SECRET
      - ENV_RBX_JWT_REFRESH_SECRET=$ENV_RBX_JWT_REFRESH_SECRET
      - ENV_RBX_JWT_ALGORITHM=$ENV_RBX_JWT_ALGORITHM
      - ENV_RBX_REDIS_URL=$ENV_RBX_REDIS_URL
    restart: always
    networks:
      - core_service_network

  # #=================================================================
  # # Identity Service
  # #=================================================================
  # identity-service:
  #   build:
  #     context: ../../../retail/middleware/identity.service
  #     dockerfile: Dockerfile
  #   image: "identity-service:v1"
  #   container_name: "identity_service"
  #   environment:
  #     - ENV_RBX_PORT=4010
  #     - ENV_RBX_DB_USERNAME=$ENV_RBX_DB_USERNAME
  #     - ENV_RBX_DB_PASS=$ENV_RBX_DB_PASS
  #     - ENV_RBX_DB_NAME=$ENV_RBX_DB_NAME
  #     - ENV_RBX_DB_HOST=$ENV_RBX_DB_HOST
  #     - ENV_RBX_DB_PORT=$ENV_RBX_DB_PORT
  #     - ENV_RBX_DB_TIMEOUT=$ENV_RBX_DB_TIMEOUT
  #     - ENV_RBX_DB_DIALECT=$ENV_RBX_DB_DIALECT
  #     - ENV_RBX_DB_DEBUG=$ENV_RBX_DB_DEBUG
  #     - ENV_RBX_GRAPHQL_DEBUG=$ENV_RBX_GRAPHQL_DEBUG
  #     - ENV_RBX_GRAPHQL_PLAYGROUND=$ENV_RBX_GRAPHQL_PLAYGROUND
  #     - ENV_RBX_IDENTITYX_BASE_URL=$ENV_RBX_IDENTITYX_BASE_URL
  #     - ENV_RBX_IDENTITYX_API_VERSION=$ENV_RBX_IDENTITYX_API_VERSION
  #     - ENV_RBX_IDENTITYX_TOKEN=$ENV_RBX_IDENTITYX_TOKEN
  #     - ENV_RBX_IDENTITYX_TENANT=$ENV_RBX_IDENTITYX_TENANT
  #     - ENV_RBX_IDENTITYX_USERNAME=$ENV_RBX_IDENTITYX_USERNAME
  #     - ENV_RBX_IDENTITYX_PASSWORD=$ENV_RBX_IDENTITYX_PASSWORD
  #   restart: always
  #   networks:
  #     - core_service_network
  #=================================================================
  # Compliance Service
  #=================================================================
  compliance-service:
    build:
      context: ../../../retail/middleware/template.service
      dockerfile: Dockerfile
    image: "compliance-service:v1"
    container_name: "compliance_service"
    environment:
      - ENV_RBX_PORT=5010
      - ENV_RBX_DB_USERNAME=$ENV_RBX_DB_USERNAME
      - ENV_RBX_DB_PASS=$ENV_RBX_DB_PASS
      - ENV_RBX_DB_NAME=$ENV_RBX_DB_NAME
      - ENV_RBX_DB_HOST=$ENV_RBX_DB_HOST
      - ENV_RBX_DB_PORT=$ENV_RBX_DB_PORT
      - ENV_RBX_DB_TIMEOUT=$ENV_RBX_DB_TIMEOUT
      - ENV_RBX_DB_DIALECT=$ENV_RBX_DB_DIALECT
      - ENV_RBX_DB_DEBUG=$ENV_RBX_DB_DEBUG
      - ENV_RBX_GRAPHQL_DEBUG=$ENV_RBX_GRAPHQL_DEBUG
      - ENV_RBX_GRAPHQL_PLAYGROUND=$ENV_RBX_GRAPHQL_PLAYGROUND
    restart: always
    networks:
      - core_service_network

  #=================================================================
  # User Management Service
  #=================================================================
  user-management-service:
    build:
      context: ../../../retail/middleware/entitlement.service
      dockerfile: Dockerfile
    image: "user-management-service:v1"
    container_name: "user_management_service"
    environment:
      - ENV_RBX_PORT=5020
      - ENV_RBX_DB_USERNAME=$ENV_RBX_DB_USERNAME
      - ENV_RBX_DB_PASS=$ENV_RBX_DB_PASS
      - ENV_RBX_DB_NAME=$ENV_RBX_DB_NAME
      - ENV_RBX_DB_HOST=$ENV_RBX_DB_HOST
      - ENV_RBX_DB_PORT=$ENV_RBX_DB_PORT
      - ENV_RBX_DB_TIMEOUT=$ENV_RBX_DB_TIMEOUT
      - ENV_RBX_DB_DIALECT=$ENV_RBX_DB_DIALECT
      - ENV_RBX_DB_DEBUG=$ENV_RBX_DB_DEBUG
      - ENV_RBX_GRAPHQL_DEBUG=$ENV_RBX_GRAPHQL_DEBUG
      - ENV_RBX_GRAPHQL_PLAYGROUND=$ENV_RBX_GRAPHQL_PLAYGROUND
    restart: always
    networks:
      - core_service_network

  #=================================================================
  # Notification Service
  #=================================================================
  notification-service:
    build:
      context: ../../../retail/middleware/notifications
      dockerfile: Dockerfile
    image: "notification-service:v1"
    container_name: "notification_service"
    environment:
      - ENV_RBX_PORT=5030
      - ENV_RBX_DB_USERNAME=$ENV_RBX_DB_USERNAME
      - ENV_RBX_DB_PASS=$ENV_RBX_DB_PASS
      - ENV_RBX_DB_NAME=$ENV_RBX_DB_NAME
      - ENV_RBX_DB_HOST=$ENV_RBX_DB_HOST
      - ENV_RBX_DB_PORT=$ENV_RBX_DB_PORT
      - ENV_RBX_DB_TIMEOUT=$ENV_RBX_DB_TIMEOUT
      - ENV_RBX_DB_DIALECT=$ENV_RBX_DB_DIALECT
      - ENV_RBX_DB_DEBUG=$ENV_RBX_DB_DEBUG
      - ENV_RBX_GRAPHQL_DEBUG=$ENV_RBX_GRAPHQL_DEBUG
      - ENV_RBX_GRAPHQL_PLAYGROUND=$ENV_RBX_GRAPHQL_PLAYGROUND
      - ENV_RBX_SMTP_HOST=$ENV_RBX_SMTP_HOST
      - ENV_RBX_SMTP_PORT=$ENV_RBX_SMTP_PORT
      - ENV_RBX_SMTP_IGNORETLS=$ENV_RBX_SMTP_IGNORETLS
      - ENV_RBX_SMTP_SECURE=$ENV_RBX_SMTP_SECURE
      - ENV_RBX_SMTP_USER=$ENV_RBX_SMTP_USER
      - ENV_RBX_SMTP_PASS=$ENV_RBX_SMTP_PASS
      - ENV_RBX_SMTP_SENDING_NAME=$ENV_RBX_SMTP_SENDING_NAME
      - ENV_RBX_SMTP_SENDING_EMAIL=$ENV_RBX_SMTP_SENDING_EMAIL
    restart: always
    networks:
      - core_service_network

networks:
  core_service_network:
    driver: bridge
